apiVersion: v1
kind: Service
metadata:
  name: "{{ template "elasticsearch2.fullname" . }}-api"
  labels:
    app: {{ template "elasticsearch2.name" . }}
    chart: {{ template "elasticsearch2.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: api
      protocol: TCP
      name: api
  selector:
    app: {{ template "elasticsearch2.name" . }}
    release: {{ .Release.Name }}
