apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch2.fullname" . }}
  labels:
    app: {{ template "elasticsearch2.name" . }}
    chart: {{ template "elasticsearch2.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiport }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.transportport }}
      targetPort: transport
      protocol: TCP
      name: transport
  selector:
    app: {{ template "elasticsearch2.name" . }}
    release: {{ .Release.Name }}
